apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
    project: zenith-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        project: zenith-x
    spec:
      serviceAccountName: zenith-ksa
      containers:
        - name: app
          image: asia-southeast2-docker.pkg.dev/stayrelevantid/zenith-x-registry/app:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: zenith-secrets
                  key: APP_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
