apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zenith-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: zenith-secrets
    creationPolicy: Owner
  data:
  - secretKey: APP_SECRET
    remoteRef:
      key: zenith-x-secret
