apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app
  labels:
    app: app
    project: zenith-x
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`masmasdeploy.my.id`)
      kind: Rule
      services:
        - name: app
          port: 80
  tls:
    secretName: masmasdeploy-tls
