apiVersion: v1
kind: ServiceAccount
metadata:
  name: zenith-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: zenith-x-gke-sa@stayrelevantid.iam.gserviceaccount.com
  labels:
    project: zenith-x
    env: testing
